# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Cache .yarn/cache for faster installs
- task: Cache@2
  displayName: Cache .yarn/cache
  inputs:
      key: 'yarn | $(Agent.OS) | yarn.lock'
      restoreKeys: |
        yarn | $(Agent.OS)
        yarn
      path: .yarn/cache
      
- task: NodeTool@0
  inputs:
    versionSpec: '18.13.0'
  displayName: 'Install Node.js'
# Enable Corepack
- task: CmdLine@2
  displayName: 'Enable Corepack'
  inputs:
    script: corepack enable

# Install Dependencies
- task: CmdLine@2
  displayName: 'Install Dependencies'
  inputs:
    script: yarn --immutable
# Building Application
- task: CmdLine@2
  displayName: 'Building application'
  inputs:
    script: yarn build

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/node_modules'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/dist/node_modules'
# Compressing and copying Sotrybook file
- task: ArchiveFiles@2
  displayName: 'Archive Storybook File '
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/API-$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy Storybook File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: 'API-$(Build.BuildId).zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact:'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished'
    ArtifactName: 'Build'
    publishLocation: 'Container'
